sonar.projectKey=salonbrenns_ProyectoBrenns
sonar.organization=salonbrenns
sonar.host.url=https://sonarcloud.io

# Solo escanear el código fuente real
sonar.sources=src

# Excluir archivos que no deben analizarse
sonar.exclusions=**/*.d.ts,**/node_modules/**,**/.next/**,**/prisma/**,**/public/**,**/*.config.js,**/*.config.ts,**/*.config.mjs

# Cobertura
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/**/*, **/*.d.ts, **/.next/**