name: Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ← necesario para SonarCloud

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Instalar dependencias
        run: npm ci --ignore-scripts || npm install --ignore-scripts

      - name: Ejecutar pruebas y cobertura   # ← NUEVO
        run: npm run test:coverage

      - name: Ejecutar ESLint Security
        run: npx eslint . || true

      - name: Instalar Snyk
        run: npm install -g snyk --ignore-scripts

      - name: Ejecutar Snyk
        run: snyk test --org=salonbrenns || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Ejecutar SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}