name: Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar ESLint Security
        run: npx eslint . || true

      - name: Instalar Snyk
        run: npm install -g snyk

      - name: Autenticar Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Ejecutar Snyk
        run: snyk test

      - name: Ejecutar SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
